"""test

Revision ID: 0988d714ca4d
Revises: 5b894b4e3131
Create Date: 2025-09-08 00:04:43.085870

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0988d714ca4d"
down_revision: Union[str, Sequence[str], None] = "5b894b4e3131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
