"""Regenerated revision

Revision ID: 3ead7a63e898
Revises:
Create Date: 2026-07-03 11:09:24.043240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3ead7a63e898"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("foundation_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Team_name"), "Team", ["name"], unique=True)
    op.create_table(
        "Player",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dob", sa.DateTime(), nullable=False),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["Team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Player_name"), "Player", ["name"], unique=False)
    op.create_index(op.f("ix_Player_position"), "Player", ["position"], unique=False)
    op.create_index(op.f("ix_Player_team_name"), "Player", ["team_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Player_team_name"), table_name="Player")
    op.drop_index(op.f("ix_Player_position"), table_name="Player")
    op.drop_index(op.f("ix_Player_name"), table_name="Player")
    op.drop_table("Player")
    op.drop_index(op.f("ix_Team_name"), table_name="Team")
    op.drop_table("Team")
    # ### end Alembic commands ###
