"""test

Revision ID: 8bbc8be31bde
Revises: 99ca765a6386
Create Date: 2025-09-25 14:49:27.811008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bbc8be31bde"
down_revision: Union[str, Sequence[str], None] = "99ca765a6386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Player_name"), table_name="Player")
    op.drop_index(op.f("ix_Player_position"), table_name="Player")
    op.drop_index(op.f("ix_Player_team"), table_name="Player")
    op.drop_table("Player")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Player",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dob", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("position", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("team", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("test", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("Player_pkey")),
    )
    op.create_index(op.f("ix_Player_team"), "Player", ["team"], unique=False)
    op.create_index(op.f("ix_Player_position"), "Player", ["position"], unique=False)
    op.create_index(op.f("ix_Player_name"), "Player", ["name"], unique=True)
    # ### end Alembic commands ###
