"""Description of your changes

Revision ID: a2cd8d9d4e52
Revises: 0988d714ca4d
Create Date: 2025-09-08 00:05:43.178818

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a2cd8d9d4e52"
down_revision: Union[str, Sequence[str], None] = "0988d714ca4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Player_name"), table_name="Player")
    op.create_index(op.f("ix_Player_name"), "Player", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Player_name"), table_name="Player")
    op.create_index(op.f("ix_Player_name"), "Player", ["name"], unique=False)
    # ### end Alembic commands ###
