"""test

Revision ID: a752585c2786
Revises: a2cd8d9d4e52
Create Date: 2025-09-08 00:11:38.242746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a752585c2786"
down_revision: Union[str, Sequence[str], None] = "a2cd8d9d4e52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Player", sa.Column("test", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Player", "test")
    # ### end Alembic commands ###
