"""test

Revision ID: e0d7c40525b1
Revises: 82daf4ea1460
Create Date: 2025-09-07 23:50:29.754975

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e0d7c40525b1"
down_revision: Union[str, Sequence[str], None] = "82daf4ea1460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
